version: "2"
services:
  mysql:
    image: "mysql"
    container_name: "docker_mysql_1"
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    mem_limit: 1000000000
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  mongo:
    image: mongo
    container_name: "docker_mongo_1"
    ports:
    - 27017:27017
    mem_limit: 1000000000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  neo4j:
    image: neo4j
    container_name: "docker_neo4j_1"
    ports:
    - 7474:7474 # - Browser explorer
    - 7687:7687 # - Bolt
    mem_limit: 1000000000
    volumes:
    - ./neo4j/data:/data
    environment:
    - NEO4J_AUTH=none
  cassandra:
    image: cassandra
    container_name: "docker_cassandra_1"
    ports: 
    - 7000:7000
    - 9042:9042
  elastic:
    image: elasticsearch:7.4.2
    container_name: elasticsearch
    ports:
    - 9200:9200 # - API
    - 9300:9300 # - Comunicacion entre nodos
    mem_limit: 1000000000
    environment:
    - discovery.type=single-node
    expose:
    - "9200"
  kibana:
    image: kibana:7.4.2
    container_name: "docker_kibana_1"
    environment:
    - SERVER_NAME=kibana.localhost
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ELASTIC_PWD=changeme
    - KIBANA_PWD=changeme
    ports:
    - 5601:5601
    expose: 
    - "5601"
    mem_limit: 1000000000
    links:
    - elastic
    depends_on:
    - elastic